import pyarrow as pa

schemas = {
    "call_center": pa.schema(
        [
            pa.field("cc_call_center_sk", pa.int64(), nullable=False),
            pa.field("cc_call_center_id", pa.string(), nullable=False),
            pa.field("cc_rec_start_date", pa.date32(), nullable=True),
            pa.field("cc_rec_end_date", pa.date32(), nullable=True),
            pa.field("cc_closed_date_sk", pa.int32(), nullable=True),
            pa.field("cc_open_date_sk", pa.int32(), nullable=True),
            pa.field("cc_name", pa.string(), nullable=False),
            pa.field("cc_class", pa.string(), nullable=False),
            pa.field("cc_employees", pa.int32(), nullable=False),
            pa.field("cc_sq_ft", pa.int32(), nullable=False),
            pa.field("cc_hours", pa.string(), nullable=False),
            pa.field("cc_manager", pa.string(), nullable=False),
            pa.field("cc_mkt_id", pa.int32(), nullable=False),
            pa.field("cc_mkt_class", pa.string(), nullable=False),
            pa.field("cc_mkt_desc", pa.string(), nullable=False),
            pa.field("cc_market_manager", pa.string(), nullable=False),
            pa.field("cc_division", pa.int32(), nullable=False),
            pa.field("cc_division_name", pa.string(), nullable=False),
            pa.field("cc_company", pa.int32(), nullable=False),
            pa.field("cc_company_name", pa.string(), nullable=False),
            pa.field("cc_street_number", pa.string(), nullable=False),
            pa.field("cc_street_name", pa.string(), nullable=False),
            pa.field("cc_street_type", pa.string(), nullable=False),
            pa.field("cc_suite_number", pa.string(), nullable=False),
            pa.field("cc_city", pa.string(), nullable=False),
            pa.field("cc_county", pa.string(), nullable=False),
            pa.field("cc_state", pa.string(), nullable=False),
            pa.field("cc_zip", pa.string(), nullable=False),
            pa.field("cc_country", pa.string(), nullable=False),
            pa.field("cc_gmt_offset", pa.decimal128(21, 2), nullable=False),
            pa.field("cc_tax_percentage", pa.decimal128(21, 2), nullable=False),
        ]
    ),
    "catalog_page": pa.schema(
        [
            pa.field("cp_catalog_page_sk", pa.int64(), nullable=False),
            pa.field("cp_catalog_page_id", pa.string(), nullable=False),
            pa.field("cp_start_date_sk", pa.int32(), nullable=True),
            pa.field("cp_end_date_sk", pa.int32(), nullable=True),
            pa.field("cp_department", pa.string(), nullable=True),
            pa.field("cp_catalog_number", pa.int32(), nullable=True),
            pa.field("cp_catalog_page_number", pa.int32(), nullable=True),
            pa.field("cp_description", pa.string(), nullable=True),
            pa.field("cp_type", pa.string(), nullable=True),
        ]
    ),
    "catalog_returns": pa.schema(
        [
            pa.field("cr_returned_date_sk", pa.int32(), nullable=False),
            pa.field("cr_returned_time_sk", pa.int64(), nullable=False),
            pa.field("cr_item_sk", pa.int64(), nullable=False),
            pa.field("cr_refunded_customer_sk", pa.int64(), nullable=True),
            pa.field("cr_refunded_cdemo_sk", pa.int64(), nullable=True),
            pa.field("cr_refunded_hdemo_sk", pa.int64(), nullable=True),
            pa.field("cr_refunded_addr_sk", pa.int64(), nullable=True),
            pa.field("cr_returning_customer_sk", pa.int64(), nullable=True),
            pa.field("cr_returning_cdemo_sk", pa.int64(), nullable=True),
            pa.field("cr_returning_hdemo_sk", pa.int64(), nullable=True),
            pa.field("cr_returning_addr_sk", pa.int64(), nullable=True),
            pa.field("cr_call_center_sk", pa.int64(), nullable=True),
            pa.field("cr_catalog_page_sk", pa.int64(), nullable=True),
            pa.field("cr_ship_mode_sk", pa.int64(), nullable=True),
            pa.field("cr_warehouse_sk", pa.int64(), nullable=True),
            pa.field("cr_reason_sk", pa.int64(), nullable=True),
            pa.field("cr_order_number", pa.int64(), nullable=False),
            pa.field("cr_return_quantity", pa.int32(), nullable=True),
            pa.field("cr_return_amount", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_return_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_return_amt_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_fee", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_return_ship_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_refunded_cash", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_reversed_charge", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_store_credit", pa.decimal128(7, 2), nullable=True),
            pa.field("cr_net_loss", pa.decimal128(7, 2), nullable=True),
        ]
    ),
    "catalog_sales": pa.schema(
        [
            pa.field("cs_sold_date_sk", pa.int32(), nullable=True),
            pa.field("cs_sold_time_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_date_sk", pa.int32(), nullable=True),
            pa.field("cs_bill_customer_sk", pa.int64(), nullable=True),
            pa.field("cs_bill_cdemo_sk", pa.int64(), nullable=True),
            pa.field("cs_bill_hdemo_sk", pa.int64(), nullable=True),
            pa.field("cs_bill_addr_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_customer_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_cdemo_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_hdemo_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_addr_sk", pa.int64(), nullable=True),
            pa.field("cs_call_center_sk", pa.int64(), nullable=True),
            pa.field("cs_catalog_page_sk", pa.int64(), nullable=True),
            pa.field("cs_ship_mode_sk", pa.int64(), nullable=True),
            pa.field("cs_warehouse_sk", pa.int64(), nullable=True),
            pa.field("cs_item_sk", pa.int64(), nullable=False),
            pa.field("cs_promo_sk", pa.int64(), nullable=True),
            pa.field("cs_order_number", pa.int64(), nullable=False),
            pa.field("cs_quantity", pa.int32(), nullable=True),
            pa.field("cs_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_discount_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_coupon_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_ext_ship_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_net_paid", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_net_paid_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_net_paid_inc_ship", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_net_paid_inc_ship_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("cs_net_profit", pa.decimal128(7, 2), nullable=False),
        ]
    ),
    "customer_address": pa.schema(
        [
            pa.field("ca_address_sk", pa.int64(), nullable=False),
            pa.field("ca_address_id", pa.string(), nullable=False),
            pa.field("ca_street_number", pa.string(), nullable=True),
            pa.field("ca_street_name", pa.string(), nullable=True),
            pa.field("ca_street_type", pa.string(), nullable=True),
            pa.field("ca_suite_number", pa.string(), nullable=True),
            pa.field("ca_city", pa.string(), nullable=True),
            pa.field("ca_county", pa.string(), nullable=True),
            pa.field("ca_state", pa.string(), nullable=True),
            pa.field("ca_zip", pa.string(), nullable=True),
            pa.field("ca_country", pa.string(), nullable=True),
            pa.field("ca_gmt_offset", pa.decimal128(21, 2), nullable=True),
            pa.field("ca_location_type", pa.string(), nullable=True),
        ]
    ),
    "customer_demographics": pa.schema(
        [
            pa.field("cd_demo_sk", pa.int64(), nullable=False),
            pa.field("cd_gender", pa.string(), nullable=False),
            pa.field("cd_marital_status", pa.string(), nullable=False),
            pa.field("cd_education_status", pa.string(), nullable=False),
            pa.field("cd_purchase_estimate", pa.int32(), nullable=False),
            pa.field("cd_credit_rating", pa.string(), nullable=False),
            pa.field("cd_dep_count", pa.int32(), nullable=False),
            pa.field("cd_dep_employed_count", pa.int32(), nullable=False),
            pa.field("cd_dep_college_count", pa.int32(), nullable=False),
        ]
    ),
    "customer": pa.schema(
        [
            pa.field("c_customer_sk", pa.int64(), nullable=False),
            pa.field("c_customer_id", pa.string(), nullable=False),
            pa.field("c_current_cdemo_sk", pa.int64(), nullable=True),
            pa.field("c_current_hdemo_sk", pa.int64(), nullable=True),
            pa.field("c_current_addr_sk", pa.int64(), nullable=True),
            pa.field("c_first_shipto_date_sk", pa.int32(), nullable=True),
            pa.field("c_first_sales_date_sk", pa.int32(), nullable=True),
            pa.field("c_salutation", pa.string(), nullable=True),
            pa.field("c_first_name", pa.string(), nullable=True),
            pa.field("c_last_name", pa.string(), nullable=True),
            pa.field("c_preferred_cust_flag", pa.string(), nullable=True),
            pa.field("c_birth_day", pa.int32(), nullable=True),
            pa.field("c_birth_month", pa.int32(), nullable=True),
            pa.field("c_birth_year", pa.int32(), nullable=True),
            pa.field("c_birth_country", pa.string(), nullable=True),
            pa.field("c_login", pa.string(), nullable=True),
            pa.field("c_email_address", pa.string(), nullable=True),
            pa.field("c_last_review_date", pa.string(), nullable=True),
        ]
    ),
    "date_dim": pa.schema(
        [
            pa.field("d_date_sk", pa.int32(), nullable=False),
            pa.field("d_date_id", pa.string(), nullable=False),
            pa.field("d_date", pa.date32(), nullable=False),
            pa.field("d_month_seq", pa.int32(), nullable=False),
            pa.field("d_week_seq", pa.int32(), nullable=False),
            pa.field("d_quarter_seq", pa.int32(), nullable=False),
            pa.field("d_year", pa.int32(), nullable=False),
            pa.field("d_dow", pa.int32(), nullable=False),
            pa.field("d_moy", pa.int32(), nullable=False),
            pa.field("d_dom", pa.int32(), nullable=False),
            pa.field("d_qoy", pa.int32(), nullable=False),
            pa.field("d_fy_year", pa.int32(), nullable=False),
            pa.field("d_fy_quarter_seq", pa.int32(), nullable=False),
            pa.field("d_fy_week_seq", pa.int32(), nullable=False),
            pa.field("d_day_name", pa.string(), nullable=False),
            pa.field("d_quarter_name", pa.string(), nullable=False),
            pa.field("d_holiday", pa.string(), nullable=False),
            pa.field("d_weekend", pa.string(), nullable=False),
            pa.field("d_following_holiday", pa.string(), nullable=False),
            pa.field("d_first_dom", pa.int32(), nullable=False),
            pa.field("d_last_dom", pa.int32(), nullable=False),
            pa.field("d_same_day_ly", pa.int32(), nullable=False),
            pa.field("d_same_day_lq", pa.int32(), nullable=False),
            pa.field("d_current_day", pa.string(), nullable=False),
            pa.field("d_current_week", pa.string(), nullable=False),
            pa.field("d_current_month", pa.string(), nullable=False),
            pa.field("d_current_quarter", pa.string(), nullable=False),
            pa.field("d_current_year", pa.string(), nullable=False),
        ]
    ),
    "household_demographics": pa.schema(
        [
            pa.field("hd_demo_sk", pa.int64(), nullable=False),
            pa.field("hd_income_band_sk", pa.int64(), nullable=False),
            pa.field("hd_buy_potential", pa.string(), nullable=False),
            pa.field("hd_dep_count", pa.int32(), nullable=False),
            pa.field("hd_vehicle_count", pa.int32(), nullable=False),
        ]
    ),
    "inventory": pa.schema(
        [
            pa.field("inv_date_sk", pa.int32(), nullable=False),
            pa.field("inv_item_sk", pa.int64(), nullable=False),
            pa.field("inv_warehouse_sk", pa.int64(), nullable=False),
            pa.field("inv_quantity_on_hand", pa.int32(), nullable=True),
        ]
    ),
    "item": pa.schema(
        [
            pa.field("i_item_sk", pa.int64(), nullable=False),
            pa.field("i_item_id", pa.string(), nullable=False),
            pa.field("i_rec_start_date", pa.string(), nullable=True),
            pa.field("i_rec_end_date", pa.string(), nullable=True),
            pa.field("i_item_desc", pa.string(), nullable=True),
            pa.field("i_current_price", pa.decimal128(7, 2), nullable=True),
            pa.field("i_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("i_brand_id", pa.int32(), nullable=True),
            pa.field("i_brand", pa.string(), nullable=True),
            pa.field("i_class_id", pa.int32(), nullable=True),
            pa.field("i_class", pa.string(), nullable=True),
            pa.field("i_category_id", pa.int32(), nullable=True),
            pa.field("i_category", pa.string(), nullable=True),
            pa.field("i_manufact_id", pa.int32(), nullable=True),
            pa.field("i_manufact", pa.string(), nullable=True),
            pa.field("i_size", pa.string(), nullable=True),
            pa.field("i_formulation", pa.string(), nullable=True),
            pa.field("i_color", pa.string(), nullable=True),
            pa.field("i_units", pa.string(), nullable=True),
            pa.field("i_container", pa.string(), nullable=True),
            pa.field("i_manager_id", pa.int32(), nullable=True),
            pa.field("i_product_name", pa.string(), nullable=True),
        ]
    ),
    "promotion": pa.schema(
        [
            pa.field("p_promo_sk", pa.int64(), nullable=False),
            pa.field("p_promo_id", pa.string(), nullable=False),
            pa.field("p_start_date_sk", pa.int32(), nullable=True),
            pa.field("p_end_date_sk", pa.int32(), nullable=True),
            pa.field("p_item_sk", pa.int64(), nullable=True),
            pa.field("p_cost", pa.decimal128(15, 2), nullable=True),
            pa.field("p_response_target", pa.int32(), nullable=True),
            pa.field("p_promo_name", pa.string(), nullable=True),
            pa.field("p_channel_dmail", pa.string(), nullable=True),
            pa.field("p_channel_email", pa.string(), nullable=True),
            pa.field("p_channel_catalog", pa.string(), nullable=True),
            pa.field("p_channel_tv", pa.string(), nullable=True),
            pa.field("p_channel_radio", pa.string(), nullable=True),
            pa.field("p_channel_press", pa.string(), nullable=True),
            pa.field("p_channel_event", pa.string(), nullable=True),
            pa.field("p_channel_demo", pa.string(), nullable=True),
            pa.field("p_channel_details", pa.string(), nullable=True),
            pa.field("p_purpose", pa.string(), nullable=True),
            pa.field("p_discount_active", pa.string(), nullable=True),
        ]
    ),
    "reason": pa.schema(
        [
            pa.field("r_reason_sk", pa.int64(), nullable=False),
            pa.field("r_reason_id", pa.string(), nullable=False),
            pa.field("r_reason_desc", pa.string(), nullable=False),
        ]
    ),
    "ship_mode": pa.schema(
        [
            pa.field("sm_ship_mode_sk", pa.int64(), nullable=False),
            pa.field("sm_ship_mode_id", pa.string(), nullable=False),
            pa.field("sm_type", pa.string(), nullable=False),
            pa.field("sm_code", pa.string(), nullable=False),
            pa.field("sm_carrier", pa.string(), nullable=False),
            pa.field("sm_contract", pa.string(), nullable=False),
        ]
    ),
    "store_returns": pa.schema(
        [
            pa.field("sr_returned_date_sk", pa.int32(), nullable=True),
            pa.field("sr_return_time_sk", pa.int64(), nullable=True),
            pa.field("sr_item_sk", pa.int64(), nullable=False),
            pa.field("sr_customer_sk", pa.int64(), nullable=True),
            pa.field("sr_cdemo_sk", pa.int64(), nullable=True),
            pa.field("sr_hdemo_sk", pa.int64(), nullable=True),
            pa.field("sr_addr_sk", pa.int64(), nullable=True),
            pa.field("sr_store_sk", pa.int64(), nullable=True),
            pa.field("sr_reason_sk", pa.int64(), nullable=True),
            pa.field("sr_ticket_number", pa.int64(), nullable=False),
            pa.field("sr_return_quantity", pa.int32(), nullable=True),
            pa.field("sr_return_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_return_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_return_amt_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_fee", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_return_ship_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_refunded_cash", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_reversed_charge", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_store_credit", pa.decimal128(7, 2), nullable=True),
            pa.field("sr_net_loss", pa.decimal128(7, 2), nullable=True),
        ]
    ),
    "store_sales": pa.schema(
        [
            pa.field("ss_sold_date_sk", pa.int32(), nullable=True),
            pa.field("ss_sold_time_sk", pa.int64(), nullable=True),
            pa.field("ss_item_sk", pa.int64(), nullable=False),
            pa.field("ss_customer_sk", pa.int64(), nullable=True),
            pa.field("ss_cdemo_sk", pa.int64(), nullable=True),
            pa.field("ss_hdemo_sk", pa.int64(), nullable=True),
            pa.field("ss_addr_sk", pa.int64(), nullable=True),
            pa.field("ss_store_sk", pa.int64(), nullable=True),
            pa.field("ss_promo_sk", pa.int64(), nullable=True),
            pa.field("ss_ticket_number", pa.int64(), nullable=False),
            pa.field("ss_quantity", pa.int32(), nullable=True),
            pa.field("ss_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_ext_discount_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_ext_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_ext_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_ext_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_ext_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_coupon_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_net_paid", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_net_paid_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("ss_net_profit", pa.decimal128(7, 2), nullable=True),
        ]
    ),
    "store": pa.schema(
        [
            pa.field("s_store_sk", pa.int64(), nullable=False),
            pa.field("s_store_id", pa.string(), nullable=False),
            pa.field("s_rec_start_date", pa.string(), nullable=True),
            pa.field("s_rec_end_date", pa.string(), nullable=True),
            pa.field("s_closed_date_sk", pa.int32(), nullable=True),
            pa.field("s_store_name", pa.string(), nullable=True),
            pa.field("s_number_employees", pa.int32(), nullable=True),
            pa.field("s_floor_space", pa.int32(), nullable=True),
            pa.field("s_hours", pa.string(), nullable=True),
            pa.field("s_manager", pa.string(), nullable=True),
            pa.field("s_market_id", pa.int32(), nullable=True),
            pa.field("s_geography_class", pa.string(), nullable=True),
            pa.field("s_market_desc", pa.string(), nullable=True),
            pa.field("s_market_manager", pa.string(), nullable=True),
            pa.field("s_division_id", pa.int32(), nullable=True),
            pa.field("s_division_name", pa.string(), nullable=True),
            pa.field("s_company_id", pa.int32(), nullable=True),
            pa.field("s_company_name", pa.string(), nullable=True),
            pa.field("s_street_number", pa.string(), nullable=True),
            pa.field("s_street_name", pa.string(), nullable=True),
            pa.field("s_street_type", pa.string(), nullable=True),
            pa.field("s_suite_number", pa.string(), nullable=True),
            pa.field("s_city", pa.string(), nullable=True),
            pa.field("s_county", pa.string(), nullable=True),
            pa.field("s_state", pa.string(), nullable=True),
            pa.field("s_zip", pa.string(), nullable=True),
            pa.field("s_country", pa.string(), nullable=True),
            pa.field("s_gmt_offset", pa.decimal128(21, 2), nullable=True),
            pa.field("s_tax_precentage", pa.decimal128(21, 2), nullable=True),
        ]
    ),
    "time_dim": pa.schema(
        [
            pa.field("t_time_sk", pa.int32(), nullable=False),
            pa.field("t_time_id", pa.string(), nullable=False),
            pa.field("t_time", pa.int32(), nullable=False),
            pa.field("t_hour", pa.int32(), nullable=False),
            pa.field("t_minute", pa.int32(), nullable=False),
            pa.field("t_second", pa.int32(), nullable=False),
            pa.field("t_am_pm", pa.string(), nullable=False),
            pa.field("t_shift", pa.string(), nullable=False),
            pa.field("t_sub_shift", pa.string(), nullable=False),
            pa.field("t_meal_time", pa.string(), nullable=True),
        ]
    ),
    "warehouse": pa.schema(
        [
            pa.field("w_warehouse_sk", pa.int64(), nullable=False),
            pa.field("w_warehouse_id", pa.string(), nullable=False),
            pa.field("w_warehouse_name", pa.string(), nullable=True),
            pa.field("w_warehouse_sq_ft", pa.int32(), nullable=True),
            pa.field("w_street_number", pa.string(), nullable=True),
            pa.field("w_street_name", pa.string(), nullable=True),
            pa.field("w_street_type", pa.string(), nullable=True),
            pa.field("w_suite_number", pa.string(), nullable=True),
            pa.field("w_city", pa.string(), nullable=True),
            pa.field("w_county", pa.string(), nullable=True),
            pa.field("w_state", pa.string(), nullable=True),
            pa.field("w_zip", pa.string(), nullable=True),
            pa.field("w_country", pa.string(), nullable=True),
            pa.field("w_gmt_offset", pa.decimal128(21, 2), nullable=True),
        ]
    ),
    "web_page": pa.schema(
        [
            pa.field("wp_web_page_sk", pa.int64(), nullable=False),
            pa.field("wp_web_page_id", pa.string(), nullable=False),
            pa.field("wp_rec_start_date", pa.string(), nullable=True),
            pa.field("wp_rec_end_date", pa.string(), nullable=True),
            pa.field("wp_creation_date_sk", pa.int32(), nullable=True),
            pa.field("wp_access_date_sk", pa.int32(), nullable=True),
            pa.field("wp_autogen_flag", pa.string(), nullable=True),
            pa.field("wp_customer_sk", pa.int64(), nullable=True),
            pa.field("wp_url", pa.string(), nullable=True),
            pa.field("wp_type", pa.string(), nullable=True),
            pa.field("wp_char_count", pa.int32(), nullable=True),
            pa.field("wp_link_count", pa.int32(), nullable=True),
            pa.field("wp_image_count", pa.int32(), nullable=True),
            pa.field("wp_max_ad_count", pa.int32(), nullable=True),
        ]
    ),
    "web_returns": pa.schema(
        [
            pa.field("wr_returned_date_sk", pa.int32(), nullable=True),
            pa.field("wr_returned_time_sk", pa.int64(), nullable=True),
            pa.field("wr_item_sk", pa.int64(), nullable=False),
            pa.field("wr_refunded_customer_sk", pa.int64(), nullable=True),
            pa.field("wr_refunded_cdemo_sk", pa.int64(), nullable=True),
            pa.field("wr_refunded_hdemo_sk", pa.int64(), nullable=True),
            pa.field("wr_refunded_addr_sk", pa.int64(), nullable=True),
            pa.field("wr_returning_customer_sk", pa.int64(), nullable=True),
            pa.field("wr_returning_cdemo_sk", pa.int64(), nullable=True),
            pa.field("wr_returning_hdemo_sk", pa.int64(), nullable=True),
            pa.field("wr_returning_addr_sk", pa.int64(), nullable=True),
            pa.field("wr_web_page_sk", pa.int64(), nullable=True),
            pa.field("wr_reason_sk", pa.int64(), nullable=True),
            pa.field("wr_order_number", pa.int64(), nullable=False),
            pa.field("wr_return_quantity", pa.int32(), nullable=True),
            pa.field("wr_return_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_return_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_return_amt_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_fee", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_return_ship_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_refunded_cash", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_reversed_charge", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_account_credit", pa.decimal128(7, 2), nullable=True),
            pa.field("wr_net_loss", pa.decimal128(7, 2), nullable=True),
        ]
    ),
    "web_sales": pa.schema(
        [
            pa.field("ws_sold_date_sk", pa.int32(), nullable=True),
            pa.field("ws_sold_time_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_date_sk", pa.int32(), nullable=True),
            pa.field("ws_item_sk", pa.int64(), nullable=False),
            pa.field("ws_bill_customer_sk", pa.int64(), nullable=True),
            pa.field("ws_bill_cdemo_sk", pa.int64(), nullable=True),
            pa.field("ws_bill_hdemo_sk", pa.int64(), nullable=True),
            pa.field("ws_bill_addr_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_customer_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_cdemo_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_hdemo_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_addr_sk", pa.int64(), nullable=True),
            pa.field("ws_web_page_sk", pa.int64(), nullable=True),
            pa.field("ws_web_site_sk", pa.int64(), nullable=True),
            pa.field("ws_ship_mode_sk", pa.int64(), nullable=True),
            pa.field("ws_warehouse_sk", pa.int64(), nullable=True),
            pa.field("ws_promo_sk", pa.int64(), nullable=True),
            pa.field("ws_order_number", pa.int64(), nullable=False),
            pa.field("ws_quantity", pa.int32(), nullable=True),
            pa.field("ws_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_discount_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_sales_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_wholesale_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_list_price", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_coupon_amt", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_ext_ship_cost", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_net_paid", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_net_paid_inc_tax", pa.decimal128(7, 2), nullable=True),
            pa.field("ws_net_paid_inc_ship", pa.decimal128(7, 2), nullable=False),
            pa.field("ws_net_paid_inc_ship_tax", pa.decimal128(7, 2), nullable=False),
            pa.field("ws_net_profit", pa.decimal128(7, 2), nullable=False),
        ]
    ),
    "web_site": pa.schema(
        [
            pa.field("web_site_sk", pa.int64(), nullable=False),
            pa.field("web_site_id", pa.string(), nullable=False),
            pa.field("web_rec_start_date", pa.string(), nullable=False),
            pa.field("web_rec_end_date", pa.string(), nullable=True),
            pa.field("web_name", pa.string(), nullable=False),
            pa.field("web_open_date_sk", pa.int32(), nullable=False),
            pa.field("web_close_date_sk", pa.int32(), nullable=True),
            pa.field("web_class", pa.string(), nullable=False),
            pa.field("web_manager", pa.string(), nullable=False),
            pa.field("web_mkt_id", pa.int32(), nullable=False),
            pa.field("web_mkt_class", pa.string(), nullable=False),
            pa.field("web_mkt_desc", pa.string(), nullable=False),
            pa.field("web_market_manager", pa.string(), nullable=False),
            pa.field("web_company_id", pa.int32(), nullable=False),
            pa.field("web_company_name", pa.string(), nullable=False),
            pa.field("web_street_number", pa.string(), nullable=False),
            pa.field("web_street_name", pa.string(), nullable=False),
            pa.field("web_street_type", pa.string(), nullable=False),
            pa.field("web_suite_number", pa.string(), nullable=False),
            pa.field("web_city", pa.string(), nullable=False),
            pa.field("web_county", pa.string(), nullable=False),
            pa.field("web_state", pa.string(), nullable=False),
            pa.field("web_zip", pa.string(), nullable=False),
            pa.field("web_country", pa.string(), nullable=False),
            pa.field("web_gmt_offset", pa.decimal128(21, 2), nullable=False),
            pa.field("web_tax_percentage", pa.decimal128(21, 2), nullable=False),
        ]
    ),
    "income_band": pa.schema(
        [
            pa.field("ib_income_band_sk", pa.int64(), nullable=False),
            pa.field("ib_lower_bound", pa.int32(), nullable=False),
            pa.field("ib_upper_bound", pa.int32(), nullable=False),
        ]
    ),
}
